### ISSUE TITLE
Couldn't find any modules

### ISSUE THREAD

**Issue by abraxxa** [miyagawa/cpan-listchanges#4]
Since about a week I'm getting "Couldn't find a module ''. Skipping" messages for all modules.
This seems to happen because http://cpanmetadb.appspot.com/v1.0/package/$distname doesn't return any data any more.

**Comment by miyagawa** [comment]
it is fixed in #3

**Comment by abraxxa** [comment]
Sorry, I didn't look at the closed issues as I clore them only after releasing a version containing the fix.
When will you release the next version?

**Comment by abraxxa** [comment]
Issue #3 is neither listed here on github when I select open or closed issues...

**Comment by miyagawa** [comment]
it's in there if you go to a pull request tab.

**Comment by abraxxa** [comment]
Ah, I didn't see that it's a pull request and not an issue, thanks!
