### ISSUE TITLE
changes files using pod format not found

### ISSUE THREAD

**Issue by y** [miyagawa/cpan-listchanges#5]
It appears that if the Change* file is in Pod format, search.cpan.org doesn't display the file link as under /src, so your regex here won't match: https://github.com/miyagawa/cpan-listchanges/blob/master/lib/App/cpanlistchanges.pm#L92

Thus, cpan-listchanges will not be able to find any changes for DBI or all the other modules from timb, and a few other authors.

Examples:
    * http://search.cpan.org/~timb/DBI-1.634/Changes
    * http://search.cpan.org/~timb/Devel-NYTProf-6.02/Changes
    * http://cpansearch.perl.org/src/TIMB/DBIx-RetryConnect-0.002002/Changes

**Comment by miyagawa** [comment]
These are not supported.

**Comment by y** [comment]
Can you elaborate on why they won't be supported? A diff would still work on these and should produce useful information for users.

**Comment by miyagawa** [comment]
I said they aren't, as of now. If you want to write a patch, that'd be all welcome.

**Comment by y** [comment]
But you closed the ticket, implying you disagreed with the idea.

**Comment by miyagawa** [comment]
I didn't imply that.

**Comment by y** [comment]
An implication is something that isn't directly said, it's something that is inferred by others. When you close a ticket, it means the ticket has nothing left to resolve. If you are open to accepting a patch, the ticket should remain open so somebody else can find it (like somebody from the CPAN Pull Request Challenge).

**Comment by miyagawa** [comment]
Sorry, I don't need an education on how to properly use github.

This software was written way before metacpan supported tracking changes. It should be much easier to write it from scratch using MetaCPAN API.

**Comment by y** [comment]
metacpan doesn't support pod Changes either, though: https://github.com/CPAN-API/metacpan-web/issues/1471

**Comment by oalders** [comment]
@y, the discussion as far as MetaCPAN goes is not closed.  I think @karenetheridge still has some thoughts on it.  If you want to comment on that issue, maybe we can make some progress on it.
